apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ./notebook/
  - ./serviceaccount/
  - ./scripts/
  - ./serving/

replacements:
- source:
    kind: ConfigMap
    name: global-demo-configs
    fieldPath: data.DSP_INSTANCE_NAME
  targets:
  - select:
      kind: Notebook
      name: mnist-notebook
    fieldPaths:
    - spec.template.spec.containers.[name=mnist-notebook].env.[name=DSP_INSTANCE_NAME].value
- source:
    kind: ConfigMap
    name: global-demo-configs
    fieldPath: data.CPU_OR_GPU_IN_NB
  targets:
  - select:
      kind: Notebook
      name: mnist-notebook
    fieldPaths:
    - spec.template.spec.containers.[name=mnist-notebook].image      
- source:
    kind: ConfigMap
    name: global-demo-configs
    fieldPath: data.NOTEBOOKS_GIT_URL
  targets:
  - select:
      kind: Notebook
      name: mnist-notebook
    fieldPaths:
    - spec.template.spec.containers.[name=mnist-notebook].env.[name=NOTEBOOKS_GIT_URL].value