resources:
  - ./openshift-data-science.yaml
  - ./openshift-pipelines.yaml
  - ./openshift-serverless.yaml
  - ./rhods-update-approbation.yaml


configMapGenerator:
- name: rhods-demo-version
  namespace: redhat-ods-operator
  envs:
  - rhods-version.env
  options:
    disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: rhods-demo-version
    namespace: redhat-ods-operator
    fieldPath: data.RHODS_VERSION
  targets:
  - select:
      kind: Subscription
      namespace: redhat-ods-operator
      name: rhods-operator
    fieldPaths:
    - spec.startingCSV