apiVersion: v1
data:
  htpasswd: aHBlX3JlZGhhdDokMnkkMDUkYjV0MEptVnJyb3hNcmJYZTlYdHhxT2JCdHYyV1I3WFZCUmY0THBsUTFobm1VZHJGTFNXS2kK
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
