apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: mnist-images
  labels:
    strimzi.io/cluster: mnist-streaming-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: mnist-scoring-results
  labels:
    strimzi.io/cluster: mnist-streaming-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824