apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: model-serving
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/adrien-legros/rhods-mnist
