kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-s3-creds
  namespace: redhat-ods-applications
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_BUCKET: rhods
  AWS_S3_ENDPOINT: http://minio-service.redhat-ods-applications.svc.cluster.local:9000/
  AWS_SECRET_ACCESS_KEY: minio123
type: Opaque
