kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-s3-creds
  namespace: mnist
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: s3-creds
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_BUCKET: rhods
  AWS_S3_ENDPOINT: http://minio-service.redhat-ods-applications.svc.cluster.local:9000/
  AWS_SECRET_ACCESS_KEY: minio123
type: Opaque
