apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: digit-recognition
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  labels:
    #networking.knative.dev/visibility: cluster-local
    opendatahub.io/dashboard: "true"
  name: digit-recognition
  namespace: mnist
spec:
  predictor:
    logger:
      mode: all
      url: http://message-dumper.mnist/
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: onnx
        version: "1"
      name: ""
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 4Gi
      runtime: digit-recognition
      storage:
        key: aws-connection-models
        path: models
