apiVersion: v2
name: mlflow-chart
description: A Helm chart for Mlflow
type: application

version: 0.1.0

appVersion: "1.25"

dependencies:
  - name: "mlflow-server"
    version: "latest"
    repository: "https://strangiato.github.io/helm-charts/"