apiVersion: v1
kind: Secret
metadata:
  name: mnist-sa
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    kubernetes.io/service-account.name: "mnist-sa"
type: kubernetes.io/service-account-token