{
 "title": "Inference Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Last Inference", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Processed Image",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT png\nFROM scoring\nORDER BY id\nDESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Associated Score",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT time, prediction, score\nFROM scoring\nORDER BY id\nDESC LIMIT 1"
    }
   ]
  },
  { "title": "All predictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "All predictions",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT time, prediction, score\nFROM scoring\nORDER BY id\nDESC"
    }
   ]
  }
 ]
}