apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: mysql-grafana-datasource
spec:
  name: mysql
  instanceSelector:
    matchLabels:
      app: grafana
  datasources:
  - access: proxy
    name: MySQL
    type: mysql
    url: mnistdb:3306
    user: mnist
    isDefault: true
    database: mnistdb
    jsonData:
      tlsSkipVerify: true
    secureJsonData:
      password: mnist