apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-a
  labels:
    dashboards: grafana-a
    folders: grafana-a
spec:
  config:
    auth:
      disable_login_form: "false"
    log:
      level: debug
      mode: console
    security:
      admin_password: admin
      admin_user: admin