apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: mnist-grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    auth:
      disable_login_form: false
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: root
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [grafana] }