apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobs
  namespace: ci-cd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-admin
subjects:
- kind: ServiceAccount
  name: jobs
  namespace: ci-cd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: configmap-appdomain
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccount: jobs
      serviceAccountName: jobs
      restartPolicy: OnFailure
      containers:
      - name: configmap-appdomain
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args:
        - -ec
        - |-
          APP_DOMAIN=$(oc get ingresses.config.openshift.io cluster -ojsonpath='{.spec.domain}')
          cat << EOF | oc apply -f-
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: appdomain
          data:
            APP_DOMAIN: ${APP_DOMAIN}