apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ds-pipeline-trigger-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: gitea-push
    interceptors:
    - params:
      - name: "eventTypes"
        value: ["pull_request"]
      ref:
        apiVersion: triggers.tekton.dev
        kind: ClusterInterceptor
        name: gitea
    name: ds-pipeline-trigger
    template:
      ref: ds-pipeline-trigger
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: ds-pipeline-trigger-listener
  name: el-ds-pipeline-trigger-listener
spec:
  port:
    targetPort: http-listener
  tls:
    termination: edge
  to:
    kind: Service
    name: el-ds-pipeline-trigger-listener
    weight: 100
  wildcardPolicy: None
