apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: mlflow-get-metrics
spec:
  description: >-
    Comment gitea PR - HTTP
  params:
  - name: DIGEST
    type: string
    description: git commit
  results:
    - name: accuracy
      type: string
    - name: loss
      type: string
    - name: lr
      type: string
    - name: val_acc
      type: string
    - name: val_loss
      type: string
  steps:
  - name: get-metrics
    image: quay.io/alegros/mnist-pipeline-exec:latest
    script: |
      #!/usr/bin/env python
      from mlflow import MlflowClient
      from mlflow.entities import ViewType
      import mlflow
      mlflow.set_tracking_uri("http://mlflow-server.mlflow.svc.cluster.local:8080")
      run = MlflowClient().search_runs(
        experiment_ids="0",
        filter_string="tags.`git.commit` = '$(params.DIGEST)'",
        max_results=1)[0]
      metrics=run.data.metrics
      with open('$(results.accuracy.path)', 'w') as f:
          f.write(repr(metrics.get("accuracy")))
      with open('$(results.loss.path)', 'w') as f:
          f.write(repr(metrics.get("loss")))
      with open('$(results.lr.path)', 'w') as f:
          f.write(repr(metrics.get("lr")))
      with open('$(results.val_acc.path)', 'w') as f:
          f.write(repr(metrics.get("val_acc")))
      with open('$(results.val_loss.path)', 'w') as f:
          f.write(repr(metrics.get("val_loss")))