apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mnist

resources:
  - ds-pipeline-instance.yaml
  - minio-route.yaml

replacements:
- source:
    kind: DataSciencePipelinesApplication
    fieldPath: metadata.name
  targets:
  - select:
      kind: Route
      name: minio
    fieldPaths:
    - spec.to.name
    options:
      delimiter: '-'
      index: 1