apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhods-mnist-core
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - component: ./operators/automated-pipelines/
        name: operators
      - component: ./manifests/openshift-pipelines/
        name: openshift-pipelines
      - component: ./manifests/gitea/      
        name: gitea
      - component: ./manifests/mlflow/      
        name: mlflow
  template:
    metadata:
      name: 'automated-pipelines-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/adrien-legros/rhods-mnist
        targetRevision: v3
        path: '{{component}}'
        directory:
          recurse: false
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        retry:
          limit: -1
        syncOptions:
        - CreateNamespace=false
        automated:
          selfHeal: true
          prune: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops