apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhods-mnist-core
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - component: ./operators/streaming/
        name: operators
      - component: ./manifests/grafana/
        name: serverless-instanciation
      - component: ./manifests/streaming/
        name: data-science-project-base
  template:
    metadata:
      name: 'streaming-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/adrien-legros/rhods-mnist
        targetRevision: v3
        path: '{{component}}'
        directory:
          recurse: false
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        retry:
          limit: -1
        syncOptions:
        - CreateNamespace=false
        automated:
          selfHeal: true
          prune: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/adrien-legros/rhods-mnist
    targetRevision: v3
    path: ./manifests/mlflow
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops