apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: mnist
  labels:
    kubernetes.io/metadata.name: mnist
    modelmesh-enabled: "true"
    opendatahub.io/dashboard: "true"
  name: mnist
