apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifests
  namespace: openshift-gitops
spec:
  source:
    repoURL: https://github.com/adrien-legros/rhods-mnist
    targetRevision: main
    path: ./operators/
  destination:
    server: https://kubernetes.default.svc
    namespace: headquarter
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops