apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mnist-view
  namespace: mnist
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: mnist-sa
  namespace: mnist