namespace: mnist

resources:
  - mariadb-password.yaml
  - networkpolicy.yaml
  - pvc.yaml
  - ds-pipeline-instance.yaml
  - minio-route.yaml

secretGenerator:
- name: aws-connection-s3-creds
  namespace: mnist
  envs:
  - minio.env
  type: Opaque
  options:
    disableNameSuffixHash: true
    labels:
      opendatahub.io/dashboard: 'true'
      opendatahub.io/managed: 'true'
    annotations:
      opendatahub.io/connection-type: s3
      openshift.io/display-name: s3-creds  

replacements:
- source:
    kind: DataSciencePipelinesApplication
    fieldPath: metadata.name
  targets:
  - select:
      kind: Route
      name: minio
    fieldPaths:
    - spec.to.name
    options:
      delimiter: '-'
      index: 1