namespace: mnist

resources:
  - ./service.yaml

patches:
- target:
    group: serving.knative.dev
    version: v1
    kind: Service
    name: data-transformation
  patch: |-
    # Modelmesh inference endpoint
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "https://mnist-mnist.apps.snogpu.redhat.hpecic.net/v2/models/mnist/infer"
    # Enable token authentication
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "true"
    # Secret name (i.e name of the service account created)
    - op: replace
      path: /spec/template/spec/containers/0/env/2/valueFrom/secretKeyRef/name
      value: "model-mesh"