apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./project/
  - ./notebook-images/
  - ./gitea/
  - ./openshift-pipelines/
  - ./ds-pipelines/
  - ./streaming/
  - ./grafana/