apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base/s3-connection.yaml
  - ./base/serving-runtime.yaml
  - ./base/inference-service.yaml
patches:
- target:
    version: v1
    kind: Secret
    name: aws-connection-s3-creds
  patch: |-
    - op: replace
      path: /stringData/AWS_S3_ENDPOINT
      value: http://minio-redhat-ods-applications.apps.CLUSTER_DOMAIN