apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobs
  namespace: mnist-kserve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-admin-mnist-kserve
subjects:
- kind: ServiceAccount
  name: jobs
  namespace: mnist-kserve
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: configmap-transformer-route
  namespace: mnist-kserve
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccount: jobs
      serviceAccountName: jobs
      restartPolicy: OnFailure
      containers:
      - name: configmap-transformer-route
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args:
        - -ec
        - |-
          TRANSFORMER_ROUTE=$(oc get ingresses.config.openshift.io cluster -ojsonpath='{.spec.domain}')
          cat << EOF | oc apply -f-
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: transformer-route
          data:
            TRANSFORMER_ROUTE: ${TRANSFORMER_ROUTE}