apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-webapp
  namespace: mnist-kserve
  labels:
    app: mnist-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-webapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mnist-webapp
    spec:
      containers:
      - image: quay.io/alegros/mnist-webapp:transformer
        imagePullPolicy: Always
        name: mnist-webapp
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: KNATIVE_SVC
          value: digit-recognition.mnist-kserve.svc.cluster.local
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mnist-webapp
  namespace: mnist-kserve
  labels:
    app: mnist-webapp
spec:
  selector:
    app: mnist-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mnist-webapp
  namespace: mnist-kserve
  labels:
    app: mnist-webapp
spec:
  port:
    targetPort: 8080 
  to:
    kind: Service
    name: mnist-webapp
  tls:
    termination: edge
  wildcardPolicy: None