apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-admin-gitea
subjects:
- kind: ServiceAccount
  name: jobs
  namespace: gitea
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io