apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: grafana
  labels:
    kubernetes.io/metadata.name: grafana
  name: grafana
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana-operator-group
  namespace: grafana
spec:
  targetNamespaces:
    - grafana
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: grafana
spec:
  channel: v5
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic