apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/red-hat-camel-k.openshift-operators: ''
  name: red-hat-camel-k
  namespace: openshift-operators
spec:
  channel: 1.10.x
  installPlanApproval: Automatic
  name: red-hat-camel-k
  source: redhat-operators
  sourceNamespace: openshift-marketplace