apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: mnist-grafana
spec:
  ingress:
    enabled: true
  deployment:
    envFrom:
      - configMapRef:
          name: grafana-plugins
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: root
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-plugins
  namespace: mnist
data:
  GF_INSTALL_PLUGINS: hamedkarbasi93-kafka-datasourcE
  envFrom:
      - configMapRef:
          name: grafana-plugins