apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: broker-to-log
spec:
  source:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: inference-logger
    properties:
      type: org.kubeflow.serving.inference.response
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: log-sink
    properties:
      showStreams: true