apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
  namespace: openshift-gitops
spec:
  applicationInstanceLabelKey: argocd.argoproj.io/instance
  project: default
  source:
    repoURL: https://github.com/adrien-legros/rhods-mnist
    targetRevision: hpe
    path: ./manifests/instances/core
  destination:
    server: https://kubernetes.default.svc
    namespace: mnist
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: false
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops