apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: openshift-gitops
spec:
  project: default
  sources:
  - repoURL: https://strangiato.github.io/helm-charts/
    chart: mlflow-server
    targetRevision: 0.5.8
    helm:
      releaseName: mnist
      valueFiles:
      - $values/manifests/instances/automated-pipelines/mlflow/values.yaml
  - repoURL: https://github.com/adrien-legros/rhods-mnist
    targetRevision: hpe
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops