apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: score-source-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: mnist-images
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: score-serialize