namespace: mnist
resources:
  - ../base/
  - ./scripts/
  - ./job.yaml

replacements:
- source:
    kind: ConfigMap
    name: global-demo-configs
    namespace: mnist
    fieldPath: data.DSP_INSTANCE_NAME
  targets:
  - select:
      kind: Job
      name: lab-reset
    fieldPaths:
    - spec.template.spec.initContainers.[name=mariadb-reset].env.[name=DSP_INSTANCE_NAME].value
  - select:
      kind: Job
      name: lab-reset
    fieldPaths:
    - spec.template.spec.containers.[name=redeploy-ds-pipeline].env.[name=DSP_INSTANCE_NAME].value
  - select:
      kind: CronJob
      name: lab-reset-cronjob
    fieldPaths:
    - spec.jobTemplate.spec.template.spec.initContainers.[name=mariadb-reset].env.[name=DSP_INSTANCE_NAME].value
  - select:
      kind: CronJob
      name: lab-reset-cronjob
    fieldPaths:
    - spec.jobTemplate.spec.template.spec.containers.[name=redeploy-ds-pipeline].env.[name=DSP_INSTANCE_NAME].value