apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitea-interceptor
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: mnist
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io