apiVersion: batch/v1
kind: Job
metadata:
  generateName: lab-solve-
  name: lab-solve
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 1800 
  backoffLimit: 6
  template:         
    metadata:
      name: lab-solve
    spec:
      serviceAccountName: jobs
      restartPolicy: OnFailure
      volumes:
        - name: solve-scripts
          configMap:
            name: lab-solve-scripts
            defaultMode: 0777 
      initContainers:
        - name: wait-for-rhods
          image: registry.redhat.io/openshift4/ose-cli:v4.11.0-202302061916.p0.g1928ac4.assembly.stream
          command: ['/scripts/wait-for-rhods.sh']
          volumeMounts:
            - name: solve-scripts
              mountPath: /scripts
      containers:
        - name: git-clone
          image: registry.redhat.io/openshift4/ose-cli:v4.11.0-202302061916.p0.g1928ac4.assembly.stream
          command: ["oc", "-n", "mnist", "exec", "-it", "po/mnist-notebook-0",  "--", "/bin/sh", "-c", "/scripts/clone-repo.sh"]
        - name: elyra-metadata
          image: registry.redhat.io/openshift4/ose-cli:v4.11.0-202302061916.p0.g1928ac4.assembly.stream
          command: ["oc", "-n", "mnist", "exec", "-it", "po/mnist-notebook-0",  "--", "/bin/sh", "-c", "/scripts/elyra-runtime.sh"]
        - name: restart-mm
          image: registry.redhat.io/openshift4/ose-cli:v4.11.0-202302061916.p0.g1928ac4.assembly.stream
          command: ['/scripts/restart-mm.sh']
          volumeMounts:
            - name: solve-scripts
              mountPath: /scripts