apiVersion: v1
kind: Secret
metadata:
  name: model-mesh
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    kubernetes.io/service-account.name: "model-server-mnist-sa"
type: kubernetes.io/service-account-token