kind: ConfigMap
apiVersion: v1
metadata:
  name: init-db
data:
  init-db.sh: |
    #!/usr/bin/env sh
    DROP TABLE IF EXISTS scoring;
    CREATE TABLE scoring(id int NOT NULL AUTO_INCREMENT, time TIMESTAMP, png VARCHAR(10000), score VARCHAR(255), prediction VARCHAR(255), PRIMARY KEY (id));
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    spec:
      serviceAccountName: jobs
      initContainers:
        - name: wait-for-mnistdb
          image: registry.redhat.io/openshift4/ose-cli:v4.11.0-202302061916.p0.g1928ac4.assembly.stream
          command: ["oc", "-n", "mnist", "wait", "--for=condition=Ready=true", "po", "-l=app=mnistdb"]
      containers:
      - name: init-db
        image: registry.redhat.io/openshift4/ose-cli:v4.11.0-202302061916.p0.g1928ac4.assembly.stream
        command: ["oc", "-n", "mnist", "exec", "-it", "dc/mnistdb",  "--", "/bin/sh", "-c", "mysql -u root mnistdb < /scripts/init-db.sh"]
      restartPolicy: Never
  backoffLimit: 4