apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: data-transformation
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
        sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    spec:
      containers:
        - image: quay.io/alegros/mnist-serverless-fn:v4
          name: serverless-function
          env:
            - name: INFERENCE_ENDPOINT
              value: "https://mnist.mnist.svc.cluster.local/v2/models/mnist/infer"
            - name: USE_OAUTH_PROXY
              value: "true"
            - name: MM_SA_NAME
              value: "mnist-sa"
            - name: OAUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mnist-sa
                  key: token
                  optional: true
            - name: KAFKA_BOOTSTRAP
              value: mnist-streaming-cluster-kafka-bootstrap.streaming.svc.cluster.local:9092
            - name: KAFKA_TOPIC
              value: mnist-scoring-results
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: mnist-images
spec:
  bootstrapServers:
    - mnist-streaming-cluster-kafka-bootstrap.streaming.svc:9092
  topics:
    - mnist-images
  sink:
    ref: 
      apiVersion: serving.knative.dev/v1
      kind: Service
      namespace: mnist
      name: data-transformation