apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: "Custom Datascience Notebook"
    opendatahub.io/notebook-image-name: "Custom Datascience Notebook"
    opendatahub.io/notebook-image-origin: Admin
    opendatahub.io/notebook-image-url: quay.io/alegros/notebook:rhods-mnist-cpu
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/notebook-image: "true"
  name: custom-ds-notebook
  namespace: redhat-ods-applications
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-python-dependencies: '[]'
      opendatahub.io/notebook-software: '[]'
      openshift.io/imported-from: quay.io/alegros/notebook:rhods-mnist-cpu
    from:
      kind: DockerImage
      name: quay.io/alegros/notebook:rhods-mnist-cpu
    importPolicy: {}
    name: rhods-mnist-cpu	
    referencePolicy:
      type: Source