kind: ConfigMap
apiVersion: v1
metadata:
  name: reset-scripts
  generateName: reset-scripts-
data:
  reset-minio.sh: |-
    #!/usr/bin/env sh
    # Create bucket
    mc alias set minio ${MINIO_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
    if [ $? -gt 0 ]; then exit 1; fi
    buckets=$(mc ls minio --json | jq '.key' | sed 's/\"//g')
    for buck in ${buckets}
    do
      echo "Removing bucket ${buck} ..."
      mc rb --force minio/${buck}
    done
    echo "Deletion phase completed"
  reset-mariadb.sh: |-
    #!/usr/bin/env sh
    mysql -h mariadb-${DSP_INSTANCE_NAME} -u mlpipeline -p${MARIADB_PWD} -D mlpipeline -e 'drop database mlpipeline';
    mysql -h mariadb-${DSP_INSTANCE_NAME} -u mlpipeline -p${MARIADB_PWD} -e 'create database mlpipeline';
  redeploy-ds-pipeline.sh: |-
    #!/usr/bin/env sh
    oc -n mnist get deploy -oname | grep ds-pipeline | xargs oc rollout restart
    oc -n mnist rollout restart deploy/mariadb-${DSP_INSTANCE_NAME}
    oc -n mnist rollout restart deploy/minio-${DSP_INSTANCE_NAME}
    oc -n mnist delete taskrun --all
  clear-mnist-namespace.sh: |-
    #!/usr/bin/env sh
    oc -n mnist delete notebook --all
    oc -n mnist delete isvc --all
    oc -n mnist delete servingruntimes --all
    oc -n mnist delete ksvc --all
    oc -n mnist delete all -l app=mnist-webapp
    oc -n mnist delete po -l component=data-science-pipelines