apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: minio-to-kafka
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: minio-source
    properties:
      accessKey: minio
      bucketName: images
      endpoint: http://minio.minio:9000
      secretKey: minio123
  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: json-serialize-stream 
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-sink
    properties:
      bootstrapServers: "mnist-streaming-cluster-kafka-bootstrap.streaming.svc:9092"
      topic: "mnist-images"
      user: kafka-user
      password: password
      securityProtocol: PLAINTEXT