apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: mnist-images
spec:
  bootstrapServers:
    - mnist-streaming-cluster-kafka-bootstrap.streaming.svc:9092
  topics:
    - mnist-images
  sink:
    ref: 
      apiVersion: serving.knative.dev/v1
      kind: Service
      namespace: mnist
      name: data-transformation