{{- if .Values.objectStorage.objectBucketClaim.enabled -}}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ include "mlflow-server.fullname" . }}
  labels:
    {{- include "mlflow-server.labels" . | nindent 4 }}
  {{- with .Values.objectStorage.objectBucketClaim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: {{ include "mlflow-server.fullname" . }}
  storageClassName: {{ .Values.objectStorage.objectBucketClaim.storageClassName }}
{{- end }}
