{{- if not .Values.objectStorage.objectBucketClaim.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow-server.fullname" . }}
  labels:
    {{- include "mlflow-server.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.objectStorage.s3AccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.objectStorage.s3SecretAccessKey | b64enc }}
{{- end }}
